import type { AlertRule } from '../types';

/** 車輛監控四態 + 多規則並列示範（套用在車輛狀態卡與新拖入的資料警示元件） */
export function vehicleStatusAlertDemoRules(): AlertRule[] {
  return [
    {
      id: 'rule-alert-msg',
      content: '{alert_message}',
      textColor: '#fff7ed',
      backgroundColor: '#c2410c',
      borderColor: '#fb923c',
      displayMode: 'blink',
      startField: 'alert_message',
      startMode: 'non-empty',
      endEnabled: false,
    },
    {
      id: 'rule-health-error',
      content: '嚴重異常：運算模組故障',
      textColor: '#fef2f2',
      backgroundColor: '#991b1b',
      borderColor: '#f87171',
      displayMode: 'blink',
      startField: 'overall_health',
      startMode: 'equals',
      startValue: 'ERROR',
      endEnabled: true,
      endField: 'overall_health',
      endMode: 'equals',
      endValue: 'OK',
    },
    {
      id: 'rule-health-warning',
      content: '車輛狀態警告 · 請持續監控',
      textColor: '#fffbeb',
      backgroundColor: '#b45309',
      borderColor: '#fbbf24',
      displayMode: 'static',
      startField: 'overall_health',
      startMode: 'equals',
      startValue: 'WARNING',
      endEnabled: false,
    },
    {
      id: 'rule-sensing-warning',
      content: '感測子系統異常',
      textColor: '#1c1917',
      backgroundColor: '#facc15',
      borderColor: '#eab308',
      displayMode: 'blink',
      startField: 'status_sensing',
      startMode: 'equals',
      startValue: 'WARNING',
      endEnabled: true,
      endField: 'status_sensing',
      endMode: 'equals',
      endValue: 'OK',
    },
    {
      id: 'rule-offline',
      content: '車輛離線 · 通訊中斷',
      textColor: '#e4e4e7',
      backgroundColor: '#52525b',
      borderColor: '#a1a1aa',
      displayMode: 'static',
      startField: 'overall_health',
      startMode: 'equals',
      startValue: 'OFFLINE',
      endEnabled: false,
    },
  ];
}
